<?php

declare(strict_types=1);

namespace BlueWolf\MinecraftToolkit\Services;

class MinecraftPropertiesService
{
    /** @param array<string, mixed> $settings */
    public function generateJava(array $settings, int $port): string
    {
        $properties = [
            'server-port' => $port,
            'query.port' => $port,
            'motd' => $this->escape((string) ($settings['motd'] ?? 'A Minecraft Server')),
            'level-name' => $this->escape((string) ($settings['level_name'] ?? 'world')),
            'max-players' => (int) ($settings['max_players'] ?? 20),
            'gamemode' => (string) ($settings['gamemode'] ?? 'survival'),
            'difficulty' => (string) ($settings['difficulty'] ?? 'easy'),
            'online-mode' => $this->boolean($settings['online_mode'] ?? true),
            'white-list' => $this->boolean($settings['whitelist'] ?? false),
            'pvp' => $this->boolean($settings['pvp'] ?? true),
            'allow-nether' => $this->boolean($settings['allow_nether'] ?? true),
            'spawn-protection' => (int) ($settings['spawn_protection'] ?? 16),
            'view-distance' => (int) ($settings['view_distance'] ?? 10),
            'simulation-distance' => (int) ($settings['simulation_distance'] ?? 10),
            'enable-command-block' => $this->boolean($settings['enable_command_block'] ?? false),
            'allow-flight' => $this->boolean($settings['allow_flight'] ?? false),
            'enable-query' => $this->boolean($settings['enable_query'] ?? false),
            'enable-rcon' => $this->boolean($settings['enable_rcon'] ?? false),
            'server-ip' => '',
        ];

        $lines = ['# Generated by Minecraft Toolkit'];
        foreach ($properties as $key => $value) {
            $lines[] = $key . '=' . $value;
        }

        return implode("\n", $lines) . "\n";
    }


    /** @param array<string, mixed> $settings */
    public function generateBedrock(array $settings, int $port): string
    {
        $properties = [
            'server-name' => (string) ($settings['motd'] ?? 'Dedicated Server'),
            'gamemode' => (string) ($settings['gamemode'] ?? 'survival'),
            'difficulty' => (string) ($settings['difficulty'] ?? 'easy'),
            'allow-cheats' => 'false',
            'max-players' => (int) ($settings['max_players'] ?? 20),
            'online-mode' => $this->boolean($settings['online_mode'] ?? true),
            'allow-list' => $this->boolean($settings['whitelist'] ?? false),
            'server-port' => $port,
            'server-portv6' => 19133,
            'view-distance' => (int) ($settings['view_distance'] ?? 10),
            'tick-distance' => max(4, min(12, (int) ($settings['simulation_distance'] ?? 10))),
            'player-idle-timeout' => 30,
            'max-threads' => 8,
            'level-name' => (string) ($settings['level_name'] ?? 'Bedrock level'),
            'level-seed' => '',
            'default-player-permission-level' => 'member',
            'texturepack-required' => 'false',
            'content-log-file-enabled' => 'false',
            'compression-threshold' => 1,
            'server-authoritative-movement' => 'server-auth',
            'player-movement-score-threshold' => 20,
            'player-movement-distance-threshold' => 0.3,
            'player-movement-duration-threshold-in-ms' => 500,
            'correct-player-movement' => 'false',
            'server-authoritative-block-breaking' => 'false',
        ];

        $lines = ['# Generated by Minecraft Toolkit for Bedrock Dedicated Server'];
        foreach ($properties as $key => $value) {
            $lines[] = $key . '=' . $this->normalize($value);
        }

        return implode("
", $lines) . "
";
    }


    /** @return array<string, string> */
    public function parse(string $contents): array
    {
        $properties = [];
        foreach (preg_split('/\R/', $contents) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) {
                continue;
            }

            [$key, $value] = explode('=', $line, 2);
            $properties[trim($key)] = trim($value);
        }

        return $properties;
    }

    /** @param array<string, mixed> $changes */
    public function patch(string $contents, array $changes): string
    {
        $lines = preg_split('/\R/', $contents) ?: [];
        $seen = [];

        foreach ($lines as &$line) {
            if ($line === '' || str_starts_with(ltrim($line), '#') || !str_contains($line, '=')) {
                continue;
            }

            [$key] = explode('=', $line, 2);
            if (!array_key_exists($key, $changes)) {
                continue;
            }

            $line = $key . '=' . $this->normalize($changes[$key]);
            $seen[$key] = true;
        }
        unset($line);

        foreach ($changes as $key => $value) {
            if (!isset($seen[$key])) {
                $lines[] = $key . '=' . $this->normalize($value);
            }
        }

        return rtrim(implode("\n", $lines)) . "\n";
    }

    private function normalize(mixed $value): string
    {
        if (is_bool($value)) {
            return $this->boolean($value);
        }

        return $this->escape((string) $value);
    }

    private function boolean(mixed $value): string
    {
        return filter_var($value, FILTER_VALIDATE_BOOLEAN) ? 'true' : 'false';
    }

    private function escape(string $value): string
    {
        return str_replace(
            ["\\", "\r", "\n", '=', ':'],
            ["\\\\", '', '\\n', '\\=', '\\:'],
            $value
        );
    }
}
